### ISSUE TITLE
Resource pack hash is not sending to client

### ISSUE THREAD

**Issue by programmerpeter** [Phoenix616/BungeeResourcepacks#4]
Resource pack is saving as `.minecraft/server-resource-packs/legacy`, but should be saved as `.minecraft/server-resource-pack/<hash>`

Config: http://pastebin.com/wfJQujJT

**Comment by Phoenix616** [comment]
Interesting. I'll definitely look into it.

**Comment by Phoenix616** [comment]
Fixed with 9eff6d7 in modules-development-branch. (will be pulled into master soon)

If you want to test it yourself you can get temporary dev-builds of that branch here: http://ci.minebench.de/job/BungeeResourcepacks%20(Modules)/
