### ISSUE TITLE
BungeeResourcepacks 1.5.4 crashes clients attempting to connect to 1.7 servers

### ISSUE THREAD

**Issue by RaynLegends** [Phoenix616/BungeeResourcepacks#6]
The latest release, which added the support to 1.9 clients, also causes players connecting to any 1.7 server under Bungeecord with the reason "Internal Server Error", throwing this exception: 

> Failed to handle packet for [IP]
> org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 16 chars (attempted 19 - 'BungeeResourcepacks.

This could be easily fixed by changed the plugin's name in bungee.yml into something with less than 16 chars, for example "BRP"

**Comment by Phoenix616** [comment]
Hm, well the plugin is aimed at version 1.8 and higher but I'll take a look if I can catch that for clients with older versions. For now I suggest you use an older version.

Renaming isn't really an option as a lot of stuff relies on that name besides the plugin message channel (permissions for example).

**Comment by RaynLegends** [comment]
Well, I tried to rename it (editing bungee.yml from the jar) and nothing broke but I can see your point. The fact is that I can't use older versions because they crash 1.9 clients but (unfortunately) I still have 1.7 servers (only accessible with 1.8, since they're running on the spigot 1.8 protocol hack and bungeecord dropped the support to 1.7 recently) and so I can't use the latest because they crash players joining those servers...
